services:
  - type: web
    name: flask-app
    env: python
    repo: https://github.com/Chirugcp/supermarket_sales_analysis
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://supermarket_sales_db_user:Vrsr0jKVl0fMaHi38z0ogBOIXJrSe7pc@dpg-cv5k7dlumphs739kq170-a.oregon-postgres.render.com/supermarket_sales_db
